version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: cobbleweb
      POSTGRES_USER: cobbleweb
      POSTGRES_PASSWORD: pwdpwd
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: