version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_db_user
      POSTGRES_PASSWORD: user_pwd
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: